# Makefile: for mcol
#  Author: Charles E. Campbell, Jr. PhD
#  Date  : July 12, 1999
# Copyright  August 25, 1999: Charles E. Campbell, Jr. -- see <Copyright> file

OBJS = error.o         mcol.o          pstrlen.o       srmtrblk.o      stpnxt.o     \
       fopenv.o        multicol.o      rdcolor.o       stpblk.o        strprintf.o  \
       ga_translate.o  outofmem.o      sprt.o          stpbrk.o        xvar.o       \
	   getarg.o

mcol : ${OBJS}
	cc ${OBJS} -o mcol
